# Site settings
title: Janice Liu portfolio
email: iceliu192@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Janice Liu's open source portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://liuliudesigns.github.io" # the base hostname & protocol for your site
twitter_username: youontwitter
github_username:  liuliudesigns

# Build settings
markdown: kramdown
